### ISSUE TITLE
companyId parameter?

### ISSUE THREAD

**Issue by lordplagus02** [Pietervdw/sageone-api-wrapper#1]
Hi there, my team and I don't really understand the purpose of the company Id parameter that goes with each of the requests. We can't find anything about it in the Sage API docs, and we'd like to contribute to this repo.

**Comment by PaulVanStaden** [comment]
So due to some design choices you can have multiple companies per set of credentials. Therefor you need to specify what company you use

**Comment by Pietervdw** [comment]
Hi There,

Paul is correct. Sage One supports multiple companies per user/set of credentials. Thus, you need to prompt the user to select the company they wish to work with before calling any api methods. You can use the **CompanyRequest ** class to get the Current company id of the logged in user. 

I've also just added two additional methods for the **CompanyRequest ** class, with which you can get all companies for the user as well as a specific company by Id.

Please take a look at the **CompanyTests ** class in the **SageOneApi.Tests** project for examples on usage.

Thank you for offering to contribute to the repo. Any help is appreciated!
